### ISSUE TITLE
Review UI cũ + Enhance

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#17]
Xem lại các UI và enhance nó tốt hơn

**Comment by NgDinhThien** [comment]
ngày 1: https://docs.google.com/document/d/1arpACs95J-rO6i1mYB3B3j2MnDSofscvFQJaicWUQG8/edit?usp=sharing

**Comment by NgDinhThien** [comment]
Ngày 2: https://docs.google.com/document/d/1oX0-xBEfYWXqO9js3-OJNIPMMEN-zTWuMvPOypddlVo/edit?usp=sharing

**Comment by NgDinhThien** [comment]
Ngày 3: https://docs.google.com/document/d/1llULZjbKdOQXvlVo6jkGEE3hhni9PhVXJHfrhi_wtgo/edit?usp=sharing

**Comment by NgDinhThien** [comment]
Ngày 4: https://docs.google.com/document/d/1v0Q42GnIFtoFp698hifERZukrp-0fUhUbgnJ9wO0ojs/edit?usp=sharing

**Comment by NgDinhThien** [comment]
Ngày 5: https://docs.google.com/document/d/1zb2ZpV8VGCmEjH8lDLXbnsIV_FXkNDl5t70WTZgUAzc/edit?usp=sharing

**Comment by NgDinhThien** [comment]
Ngày 6: https://docs.google.com/document/d/1Sb8GoEA4ZxvQ-hY_IfllciDZpN4bbmc7oZYh1NJm69I/edit?usp=sharing

**Comment by NgDinhThien** [comment]
Ngày 7: https://docs.google.com/document/d/1H4vxRS_8IFy81tbuiIHjsbgRTSwS0s4VAmaE3zkoqik/edit?usp=sharing
