### ISSUE TITLE
Tạo thêm các trang Report

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#19]
- Thêm các trang report
- Hoàn thiện các trang cũ

**Comment by SocThai** [comment]
Page Report
 - Live
 
![image](https://user-images.githubusercontent.com/126318097/236794480-8df244b2-6dc2-4d8d-90ac-2e0b1a478dd0.png)

**Comment by SocThai** [comment]
- Dashboard
![image](https://user-images.githubusercontent.com/126318097/236794739-962e5af0-fe9c-49a2-bc01-98c82810c9a6.png)

**Comment by SocThai** [comment]
- Inbound
![image](https://user-images.githubusercontent.com/126318097/236794879-aed10c66-50a9-459c-b8c4-71be14aa913b.png)

**Comment by SocThai** [comment]
- Service Level
![image](https://user-images.githubusercontent.com/126318097/236795162-0e8afcc4-c9b5-4d70-a732-6aa15931fa5c.png)

**Comment by SocThai** [comment]
- Outbound 
![image](https://user-images.githubusercontent.com/126318097/236795366-47a7507f-e58e-4e9b-ab1c-74dee31bbb24.png)

**Comment by SocThai** [comment]
- Agents 
![image](https://user-images.githubusercontent.com/126318097/236795471-feaf4cc0-7a63-444a-9dc5-73800814af34.png)
