### ISSUE TITLE
Thiết kế activity diagram

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#22]
Thiết kế thêm các diagram theo chức năng

**Comment by NgDinhThien** [comment]
**Activity Diagram for USER**

**Comment by NgDinhThien** [comment]
	Activity Diagram  Login:
![image](https://user-images.githubusercontent.com/126314213/236790938-e7fd1148-6dfd-421c-bdc7-50723a3c1a13.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram  Contact:
![image](https://user-images.githubusercontent.com/126314213/236791093-b0616a0c-7a7c-4abf-ae41-7579d0742cba.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram  Report:
![image](https://user-images.githubusercontent.com/126314213/236791162-8331ad6e-6970-4508-8f4e-f0bcf5b3645e.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram  Logout:
![image](https://user-images.githubusercontent.com/126314213/236791303-c93a1eb0-62d0-4a2b-a0e4-b332aa07f499.png)

**Comment by NgDinhThien** [comment]
**Activity Diagram for ADMIN**

**Comment by NgDinhThien** [comment]
	Activity Diagram Add Agent:
![image](https://user-images.githubusercontent.com/126314213/236791384-ed909f9e-4981-41d1-abdc-891edf26fa51.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram Edit Agent:
![image](https://user-images.githubusercontent.com/126314213/236791430-fbfddaec-896e-4d83-9b18-aa61bab45e9b.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram Delete Agent:
![image](https://user-images.githubusercontent.com/126314213/236791493-29732bf9-f9b5-403a-840b-e9c56edc1b18.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram Add Customer:
![image](https://user-images.githubusercontent.com/126314213/236791543-6fe093d4-4a43-43a9-8fb2-91cfe0633678.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram Edit Custome:
![image](https://user-images.githubusercontent.com/126314213/236791596-e97c5628-7e50-43e4-a6ba-c1e83bb9882f.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram Delete Customer:
![image](https://user-images.githubusercontent.com/126314213/236791647-19670488-ff6b-4120-8f9a-970e654d52ac.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram View Cal:
![image](https://user-images.githubusercontent.com/126314213/236791704-e712c02e-dcdf-4c15-bacf-d70d7dcbfac6.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram View Agent:
![image](https://user-images.githubusercontent.com/126314213/236791753-fdd14cd9-3216-498d-9380-e899f3f35d86.png)

**Comment by NgDinhThien** [comment]
	Activity Diagram View Customer:
![image](https://user-images.githubusercontent.com/126314213/236791817-92831926-41dc-4ef4-a8d2-30b4bfe7be45.png)
