### ISSUE TITLE
Chỉnh sửa FE

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#24]
- Chỉnh sửa FE các trang report cho chức năng lọc
- Chỉnh sửa FE trang call detaild

**Comment by SocThai** [comment]
Chỉnh sửa css cho các trang report lọc theo ngày tháng năm
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126318097/ee53b2cb-cb84-44ac-9d66-ed501d8d0d26)

**Comment by SocThai** [comment]
Tạo thanh cuộn cho Contact List
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126318097/290b3189-22c9-49a1-8bc8-351326f7905d)

**Comment by SocThai** [comment]
chỉnh sửa trang call detail
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126318097/4f32d1d2-d300-46fa-a63d-7590ea22d85f)
