### ISSUE TITLE
Thực hiện manual testing

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#25]
- Kiểm thử các chức năng cho agent
- Kiểm thử các chức năng cho manager

**Comment by NgDinhThien** [comment]
Trong nhiệm vụ này sẽ thực hiện test tất cả các chức năng của chương trình

**Comment by NgDinhThien** [comment]
ở header, khi ở trang nào thì phần header chứa nội dung đó có hiệu ứng hover
thêm script để xử lý:
<script>
	document.addEventListener('DOMContentLoaded', function() {
		var currentUrl = window.location.href;
		var url = new URL(currentUrl);
		
		var path = url.pathname;
		var textUrl = '';
		$('#main-menu li a').each(function() {
			if ($(this).attr('href') === path) {
				textUrl = $(this).text().trim();
				console.log("20110263c: ", textUrl);
				return false; // Dừng vòng lặp nếu tìm thấy mục
			}
		});
		var activeMenuItem = textUrl;
		
		
		var path2 = "/"+ url.pathname.split('/')[1];
		var textUrl2 = '';
		$('#main-menu li a').each(function() {
			if ($(this).attr('href') === path2) {
				textUrl2 = $(this).text().trim();
				console.log("20110263b: ", textUrl2);
				return false; // Dừng vòng lặp nếu tìm thấy mục
			}
		});
		var activeMenuItem2 = textUrl2;
		
		var menuItems = document.querySelectorAll('#main-menu li');
		menuItems.forEach(function(item) {
			var menuItemText = item.querySelector('a').textContent.trim();	
			if (menuItemText === activeMenuItem || menuItemText === activeMenuItem2) {
				item.classList.add('active');
			} else {
				item.classList.remove('active');
			}
		});
	});
</script>

**Comment by NgDinhThien** [comment]
xử lý ngoại lệ ở font-end và điều hướng web khi có ngoại lệ:
<c:if test="${not empty message}">
				<div class="alert alert-danger">
				${message}
				<span class="close-btn" id="closeAlertBtn">&times;</span>
				</div>
			</c:if>
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/ae4b7d2b-b4e2-4c5d-a28e-09c070437650)
@PostMapping("/signup")
	public String signUp(Model model, @Validated @RequestParam("email") String email,
			@Validated @RequestParam("password") String password) {
		Optional<Agent> optAgent = agentRepository.findByEmail(email);

		if (optAgent.isPresent()) {
			model.addAttribute("message", "Tài khoản email này đã tồn tại trong hệ thống");
			return "signup";
		} else {
			Agent agent = new Agent();
			Date date = new Date(System.currentTimeMillis());
			Timestamp ts = new Timestamp(date.getTime());

			agent.setEmail(email.trim());
			agent.setPassword(password.trim());
			agent.setCreateAt(ts);
			agentRepository.save(agent);

			return "redirect:/login";
		}
	}

**Comment by NgDinhThien** [comment]
xử lý ngoại lệ cho đăng nhập:
	<c:if test="${not empty message}">
				<div class="alert alert-danger">
				${message}
				<span class="close-btn" id="closeAlertBtn">&times;</span>
				</div>
			</c:if>
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/0e94fc16-292f-49b7-af61-b7d4f77b75c3)
@PostMapping("/login")
	public String home(Model model, @RequestParam("email") String email, @RequestParam("password") String password,
			HttpSession session) {
		Optional<Agent> optAgent = agentRepository.findByEmail(email);

		if (optAgent.isEmpty()) {
			model.addAttribute("message", "Tài khoản hoặc mật khẩu không chính xác");
			return "login";
		} else {
			if (optAgent.get().getPassword().equals(password)) {
				//model.addAttribute("message", "Đăng nhập thành công");
				session.setAttribute("user", optAgent.get());
				return "redirect:/";				
			} else {
				model.addAttribute("message", "Tài khoản hoặc mật khẩu không chính xác");
				return "login";
			}
		}
	}

**Comment by NgDinhThien** [comment]
các chức năng của Agent:
home:
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/6e2ddec3-4364-47ce-968a-2e73b00793c9)
call history: hoạt động tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/dce92b94-8a97-4a7b-a03f-ab18892733f1)
thực hiện tìm kiếm bằng phone number trên callhistory: hoạt động tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/b864ae9a-12ad-4566-ab03-ca42088f2c38)
chức năng contact, tìm kiếm bằng phone number trên contact: hoạt động tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/bcf519dd-d207-4d76-ae17-8d971fbd5334)
lần lượt kiểm tra các chức năng trong report:
Live: các chức năng duyệt theo ngày cũng hoạt động tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/ed0c7143-15a0-4466-8bd6-7d8523ce5ed2)
dashboard: các chức năng duyệt theo ngày cũng hoạt động tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/a5b5bd88-fb19-454d-a7ba-5a3b60e5dfa5)
Inbound: các chức năng duyệt theo ngày cũng hoạt động tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/6dbbd8af-f781-49ef-b7ba-1b4a127e9e01)
Service level: tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/a8c7ac5a-a232-459d-89a9-54266ad15f10)
Outbound:  tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/a44fa2b6-826f-4402-b543-07302dc9f1db)
Agents: tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/95342152-c32c-4d2c-a9d4-ee4db30ced77)
Calls: tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/1750dfbd-0308-4ea6-a407-20ab89010e50)

**Comment by NgDinhThien** [comment]
test các chức năng của manager:
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/36d1a95a-197c-4f59-a28c-7b477784ca51)

**Comment by NgDinhThien** [comment]
Ngoài những chức năng tương tự của Agent đã hoạt động tốt thì Magager có thêm những chức năng quản lý riêng
Đối với Manage Agent:
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/021a950d-f6b4-44c7-a5e6-4ae7ad84c8ca)
- phân trang hoạt động tốt, hiển thị được dữ liệu:
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/f66a497e-21f2-423f-afba-536a8aa339c1)
chức năng thêm Agent:
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/cbe4c686-da88-4063-bd68-79148f1c6036)
- thành công thêm vào 1 agent, ngoài ra có thể thêm manager khi chọn Choose level ở bước điền thông tin
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/77bbc668-2845-40fc-8569-1018ca22c1c4)

**Comment by NgDinhThien** [comment]
tương tự với chức năng trên thì Manage Customer cũng hoạt động tốt khi có thể show dữ liệu, phân trang, thêm sửa xóa Customer đều hoạt động tốt

**Comment by NgDinhThien** [comment]
thêm: tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/96e7059b-a5ff-4d0a-94dc-63b2bd271ddd)
sửa: tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/6efa362c-a865-489a-a60c-48a7d4a68595)
xóa: tốt
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/9034f2bc-b89c-4066-9529-4331ccccfc98)

**Comment by NgDinhThien** [comment]
đối với Manage Call thì các chức năng cũng hoạt động tốt

**Comment by NgDinhThien** [comment]
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/0e838f0f-28ff-4377-a454-37b472c83064)
khi add: điền đầy đủ thông tin và chọn file mp3 thì thêm thành công
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/43fc8cf9-a9cb-44b5-bdfa-e1388d406b13)

**Comment by NgDinhThien** [comment]
các chức năng sửa xóa cũng hoạt động tốt, ngoài ra có thể nghe lại lịch sửa cuộc gọi:
![image](https://github.com/20110665/Customer-Experience-Analytics/assets/126314213/923df98c-0f49-426c-88dd-acc9faeec48d)
