### ISSUE TITLE
Xác định ngôn ngữ và framewok

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#3]
Xác định ngôn ngữ sẽ sử dụng cũng như framewok
Các công cụ hỗ trợ (nếu có giải thích cách cài đặt)

**Comment by NgDinhThien** [comment]
[Xác định ngôn ngữ và framework.docx](https://github.com/20110665/Customer-Experience-Analytics/files/11008847/Xac.d.nh.ngon.ng.va.framework.docx)

**Comment by NgDinhThien** [comment]
ngày 1 tìm hiểu đề tài
ngày 2 phân tích các thành phần chính của đề tài
ngày 3 phân tích các phần còn lại của đề tài
ngày 4 xem cấu trúc chính của giao diện
ngày 5 tìm hiểu back end và cách vận hành của project
ngày 6 tìm hiểu cách vận hành của font end
ngày 7 thiết kế figma cho giao diện
