### ISSUE TITLE
Vẽ usercase diagram, class diagram

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#4]
* Vẽ usercase diagram
* Vẽ class diagram
* Lưu ý: Vẽ toàn bộ các chức năng cần có của trang web

**Comment by NgDinhThien** [comment]
Vẽ Class Diagram
Ngày 1:
-	Xác định các class
Từ kết quả của tuần trước ta có các class trong cơ sở dữ liệu bao gồm
+ Customer
+ Call
+ Call Detail
+ FeedBack Detaild
+ Agent
+ Call Conversation

**Comment by NgDinhThien** [comment]
Ngày 2:
-	Vẽ Class diagram
	+ Các tính chất cơ bản của class diagram: Tên class, Attribute (field, property), Operation (method, function)

**Comment by NgDinhThien** [comment]
![Image](https://user-images.githubusercontent.com/126314213/227798562-cc11647a-98fc-417b-a7a4-608af960adb3.png)

**Comment by NgDinhThien** [comment]
**Vẽ UserCase Diagram cho trang web:
Ngày 3:**
-	Thực hiện thiết lập ngữ cảnh của hệ thống.
-	Actor là thành phần chỉ người dùng hoặc một đối tượng nào đó bên ngoài tương tác với hệ thống
-	Ai là người sử dụng chức năng chính của hệ thống (tác nhân chính)?
-	Ai sẽ là admin của hệ thống – Người cài đặt, quản lý và bảo trì hệ thống (tác nhân phụ)?
-	Ai sẽ cần hệ thống hỗ trợ để thực hiện các tác vụ hằng ngày?
-	Use Case là các chức năng mà các Actor sẽ sử dụng hay thể hiện sự tương tác giữa người dùng và hệ thống
-	Actor cần những chức năng nào của hệ thống?
-	Actor có hành động chính là gì?
-	Actor có cần đọc, thêm mới, hủy bỏ, chỉnh sửa hay lưu trữ loại thông tin nào trong hệ thống không?
-	Hệ thống có cần thông báo những thay đổi bất ngờ trong nội bộ cho Actor không?

**Comment by NgDinhThien** [comment]
**Ngày 4:**
-	Xác định các Actor.
+ Customer
+ Agent
+ admin
-	Xác định các Use Case.
+ Call: thực hiện liên lạc với khách hàng khác
	+ History: xem lại lịch sử các cuộc gọi đến, các cuộc gọi đi, các cuộc gọi nhỡ,…
	+ Contacts: tìm kiếm thông tin liên lạc của Customer khác, xem profile của họ
	+ Report: báo cáo lỗi, báo cáo người dùng với admin
	+ feedback: đánh giá cuộc gọi
	+ ManageProfile: quản lí hồ sơ cá nhân

**Comment by NgDinhThien** [comment]
**Ngày 5:**
-	Định nghĩa các mối quan hệ giữa Actor và Use Case.
+ admin: khóa tài khoản người dùng nếu họ quy phạm vi tắt, quản lí tài khoản cá nhân
+ Customer: thực hiện các cuộc gọi, đánh giá cuộc gọi, báo cáo người dùng, quản lí tài khoản cá nhân
+ agent: quản lí các feedback, quản lí tài khoản cá nhân, thực hiện các cuộc gọi

**Comment by NgDinhThien** [comment]
**Ngày 6:**
-	Đánh giá các mối quan hệ đó để tìm cách chi tiết hóa
Kích cỡ các Use Case trong Diagram là phải như nhau, kể cả cha-con, lẫn các mối quan hệ Include. Tuy nhiên, Use Case có Extend sẽ được vẽ to hơn một chút.
Nhớ phải đánh dấu Use Case ID trong hình vẽ.
Các mối quan hệ không được chồng chéo lẫn nhau. Anh em có thể vẽ 1 Actor ở 2 vị trí khác nhau để tránh các đường nối bắt chéo lên nhau.
Khi vẽ Use Case Diagram, tập trung vào câu hỏi What để tìm ra Use Case, tránh câu hỏi How, vì khi đó anh em rất dễ đi vào detail.

**Comment by NgDinhThien** [comment]
**Ngày 7:**
-	Đánh giá các Use Case cho quan hệ Include: Include được định nghĩa là mối quan hệ bắt buộc phải có giữa các use case với nhau. Một Use case có thể chứa chức năng của một use case khác như một phần xử lý của nó. Xét về nghĩa, Include trong tiếng Anh nghĩa là bao gồm. Tức nếu nói Use Case A có mối quan hệ Include với Use Case B thì điều đó có nghĩa Use Case A bao gồm Use Case B.
-	Đánh giá các Use Case cho quan hệ Extend: Extend được định nghĩa là mối quan hệ mở rộng giữa các Use case với nhau. Nếu đối với Include là mối quan hệ bắt buộc thì Extend lại là mối quan hệ không bắt buộc, có thể có hoặc không giữa các Use case với nhau. Một Use Case B là extend của Use Case A thì có nghĩa Use Case B chỉ là một thứ optional, và chỉ xảy ra trong một hoàn cảnh cụ thể nào đó.
-	UserCase Diagram:

**Comment by NgDinhThien** [comment]
![Image](https://user-images.githubusercontent.com/126314213/227798857-6a8f47a5-639a-408a-ba72-bba52ed600ad.png)
