### ISSUE TITLE
Tạo figma theo từng màn hình 

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#5]
* Figma cho trang Login, Singup, Forget Password
* Figma cho trang home
* Figma cho các trang chức năng (...)
(50% của trang web)
Tham khảo: https://www.youtube.com/watch?v=6qOL69bIQz8&t=109s

**Comment by SocThai** [comment]
- [ ] Day 1: Tìm hiểu về figma
- [ ] Day 2: Tìm hiểu cách sử dụng figma

**Comment by SocThai** [comment]
- [ ] Day 3: Thiết kế mẫu trang login
- [ ] Day 4: Tìm hiểu các thành phần và chức năng cho trang home
- [ ] Day 5: Thiết kế trang home (heading)
- [ ] Day 6: Thiết kế trang home (content)
- [ ] Day 7:Thiết kế trang home (footer)

**Comment by SocThai** [comment]
[figma.docx](https://github.com/20110665/Customer-Experience-Analytics/files/11077306/figma.docx)
https://www.figma.com/file/9RkNl2ki9omhkaf1Oxzg9W/Untitled?node-id=0-1&t=egBESebQhOR1u396-0
