### ISSUE TITLE
Review class diagram, usercase diagram

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#7]
Xem lại và chỉnh sửa digram

**Comment by NgDinhThien** [comment]
![Image](https://user-images.githubusercontent.com/126314213/228002370-37609911-339b-4047-a7e7-149b781dc7c1.png)

**Comment by NgDinhThien** [comment]
**Ngày 1: xem lại hệ thống:**
Talkdesk: bàn đàm thoại
Nó là một call center có trách nhiệm thực hiện giao tiếp giữa khách hàng và nhân viên công ty thông qua điện thoại. Công việc của họ là tiếp nhận cuộc gọi đến và thực hiện cuộc gọi đi.
Call Center giúp cho doanh nghiệp có thể kết nối và hỗ trợ một lượng lớn khách hàng, hàng trăm cuộc gọi được chuyển đi cùng thời điểm và đều được lưu lại. Bên cạnh đó, với những doanh nghiệp cần truyền tải thông tin, dịch vụ, có chính sách khuyến mãi cho khách hàng cũng được chuyển đến khách hàng đúng thời gian.
Nói ngắn gọn thì nó là một ứng dụng chuyên dùng cho các công ty chăm sóc khách hàng, có actor chính là nhân viên chăm sóc khách hàng (khách hàng gọi đến bằng điện thoại chứ k dùng được chức năng trong ứng dụng nên nó k phải actor)

**Comment by NgDinhThien** [comment]
**Ngày 2: xác định ngữ cảnh**
Khách hàng sẽ gọi điện đến tổng đài bằng số của công ty, khi đó nhân viên nào chưa nhận cuộc gọi thì sẽ chấp nhận cuộc gọi qua Talkdesk để giao tiếp với khách hàng  tất cả các nhân viên của cùng 1 công ty thì dùng chung 1 số điện thoại(số công ty) trong ứng dụng này  sinh ra thêm actor quản lý nhân viên sẽ là giám đốc (người này có quyền như admin để thêm thông tin nhân viên và cấp quyền)

**Comment by NgDinhThien** [comment]
**Ngày 3: xác định các bảng trong csdl**
Các bảng trong cơ sở dữ liệu: (cho đến khi phân tích các ý trên)
-	Khách hàng(ID, Tên, tuổi, giới tính, số điện thoại cá nhân, địa chỉ)
-	Nhân viên(ID, Tên, tuổi, giới tính, số điện thoại cá nhân, địa chỉ)
-	Quản lý(ID, Tên, tuổi, giới tính, số điện thoại cá nhân, địa chỉ)
-	Công ty(ID, Tên, Id người quản lí, , số điện thoại công ty, địa chỉ)
-	Máy tính(ID, tên máy tính, phòng làm việc, ID nhân viên)
-	Quản lí gồm nhiều Cuộc gọi(ID, Số người gọi, ID nhân viên, mình gọi hay nó gọi, gọi nhỡ?, thời gian gọi, thời gian kết thúc, thời gian nghe máy)
-	Chi tiết cuộc gọi(ID, ?trong này có cái gì thì k biết)

**Comment by NgDinhThien** [comment]
**Ngày 4: xác định lại usecase**
Các use case có thể có:
-	Nhận cuộc gọi
-	Thực hiện cuộc gọi
-	Thêm sửa xóa nhân viên
-	Edit thông tin khách hàng
-	Xem chi tiết thông tin khách hàng
-	Xem lịch sử cuộc gọi  Lọc dữ liệu (extend)
-	Tìm kiếm cuộc gọi  Lọc dữ liệu (extend)
Tóm lại actor chính của app này là nhân viên chắm sóc khách hàng.
Còn khách hàng chỉ là dữ liệu hoặc actor tác động vào để tạo dữ liệu Cuộc gọi()

**Comment by NgDinhThien** [comment]
**Ngày 5: giải thích việc gọi điện đế hệ thống**
Khi khách hàng gọi điện đến cho công ty, thì cuộc gọi không được ngẫu nhiên kết nối đến 1 nhân viên mà dựa trên hàng chờ. Tức là hệ thống sẽ đưa những nhân viên đang có kết nối ra khỏi hàng chờ, sau đó thêm những nhân viên đã hoàn thành kết nối vào hàng chờ đến nhận cuộc gọi tiếp theo.  nhân viên có thêm thuộc tính đang gọi nếu như đang trong cuộc gọi thì không được kết nối thêm cuộc gọi khác  hàm check trước khi kết nối

**Comment by NgDinhThien** [comment]
**Ngày 6: phân tích chức năng gọi**
Chức năng gọi: truyền vào số điện thoại người gọi, số tổng đài, thời gian bắt đầu gọi
Nếu được bắt máy thì type cuộc gọi là cuộc gọi đi
Nếu không thì là cuộc gọi đi chưa được kết nối
Nếu người khác gọi đến mình mà bắt máy là cuộc gọi đến
Không bắt thì là nhỡ
Quy tắt gọi, nếu thời gian chờ kết nối quá 30s thì sẽ tự hủy  điền các thông tin còn lại vào

**Comment by NgDinhThien** [comment]
**Ngày 7: vẽ lại biểu đồ theo thiết kế**

**Comment by NgDinhThien** [comment]
![image](https://user-images.githubusercontent.com/126314213/229363867-87e49cf8-d855-4fd9-84a8-2a9154b38ca9.png)

**Comment by NgDinhThien** [comment]
![image](https://user-images.githubusercontent.com/126314213/229363876-97cfb699-b3f3-4742-af36-9827be383b50.png)
