### ISSUE TITLE
Review lại figma 

### ISSUE THREAD

**Issue by 20110665** [20110665/Customer-Experience-Analytics#8]
Review lại figma của trang web

**Comment by SocThai** [comment]
- [ ] Day 1: vẽ trang đăng ký trên figma
- [ ] Day 2: vẽ trang quên mật khẩu trên figma
- [ ] Day 3: vẽ trang quản lý thông tin khách hàng
- [ ] Day 4: vẽ trang quản lý thông tin cuộc gọi
- [ ] Day 5: vẽ trang phân tích báo cáo (live)
- [ ] Day 6: vẽ trang phân tích báo cáo (inbound)
- [ ] Day 7: viết mô tả lại UI
